### ISSUE TITLE
When two tabs opened in browser, User can still access an application from tab2 even if he logs out from tab1.

### ISSUE THREAD

**Issue by alpesh1988** [damienbod/angular-auth-oidc-client#1248] opened 2021-09-06 08:41 UTC
**Describe the bug**
when two tabs of an application opened, The user has full access on an application in one tab although the user logs out on the other tab.

**To Reproduce**
1. Open two tabs of an application in browser
2. Logout from tab 1. (It is working fine)
3. You can still use an application from tab 2 without logging in again.

**Expected behavior**
User should be logged out and asked to login all tabs.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alpesh1988** [comment] 2021-09-06 08:43
@damienbod Please take a look at this bug...

I tried to use all methods for logout like **logoff**, **logoffAndRevokeTokensbut**, **logoffLocal** but none of them worked.

**Comment by damienbod** [comment] 2021-09-06 08:52
Hi @alpesh1988 This is by design and a side effect of using refresh tokens. Each tab has a separate running session with it's own refresh token (guessing) So when you logout of one session it does logout the session, but not the other session in the other tab.

You can force a full logout on all tabs by using localstorage with a shared item which could revoke all the refresh tokens or by not using refresh tokens. Both are not perfect. 

Greetings Damien

**Comment by FabianGosebrink** [comment] 2021-09-19 14:07
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Closed by FabianGosebrink** 2021-09-19 14:07 UTC

**Comment by a-a-k** [comment] 2022-11-18 15:46
@damienbod @FabianGosebrink could you guys give a bit more info about disadvantages of both mentioned possible solutions? Why they are _not perfect_?
