### ISSUE TITLE
Invalid refresh token error (Error 401) while refreshing the session

### ISSUE THREAD

**Issue by Swarnalathaa** [damienbod/angular-auth-oidc-client#1315] opened 2021-12-01 14:08 UTC
Hi,
I am using angular-auth-oidc-client version 11 and have the following configuration 
oidcConfigService.withConfig({
      stsServer: 'https://login......',
      redirectUrl: 'http://localhost:4200',
      postLogoutRedirectUri: window.location.origin,
      clientId: 'clientId',
      scope: 'openid profile email offline_access',
      responseType: 'code',
      silentRenew: true,
      logLevel: LogLevel.Debug,
      useRefreshToken: true,
      renewTimeBeforeTokenExpiresInSeconds: 100
    });
When trying to renew the session, i am getting 401 error code with invalid refresh token error.
![Untitled](https://user-images.githubusercontent.com/34007219/144248791-96a34ba6-e77e-406c-aff0-20ae3d756dbb.png)

**Comment by damienbod** [comment] 2021-12-02 16:21
You STS returns no refresh token and so it's not defined. Using refresh tokens in the browser should support one time usage and rotation

Greetings Damien

**Comment by everflux** [comment] 2022-02-27 12:32
Seems to be a duplicate of #1338

**Closed** 2022-02-28 08:16 UTC
Labels: question, version 11
