### ISSUE TITLE
Not displaying LogoutURI instead going to the default page

### ISSUE THREAD

**Issue by ebinroy** [damienbod/angular-auth-oidc-client#1003] opened 2021-03-08 12:10 UTC
I have few pages in my app, I have given **AutoLoginGuard** for all the pages other than Dashboard (default page) and logout.

**Issue**
The logout page is not displaying. Actually it is redirecting to logout but the default page is displaying, ie dashboard

```
const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'dashboard' },  
  { path: 'service', component: MyServiceComponent , canActivate: [AutoLoginGuard] },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'logout', component: LogoutComponent }];

```

**App.Component.ts**

```
ngOnInit() {

    console.log("*** In app page ngOnInit()");

    this.authservice.IsAuthenticated$.subscribe(data =>{
      debugger;
      if(data == false){
        if ('/logout' == window.location.pathname) {
        }
        else{
          this.authservice.checkAuth().subscribe( result => {
            debugger;
            this.isAuthenticated = result;
            
          });
        }
      }
      else{
        this.isAuthenticated = data;
      }
    }
    );
}
```

**app.module.ts**

```
export function configureAuth(oidcConfigService: OidcConfigService) {
  return () =>
    oidcConfigService.withConfig({
      stsServer: 'https://localhost:5001',
      redirectUrl: window.location.origin,
      
      clientId: 'clientangular',
      scope: 'openid profile api1 offline_access',
      responseType: 'code',
      triggerAuthorizationResultEvent: true,
      postLogoutRedirectUri: 'http://localhost:4200/logout',
      
      renewTimeBeforeTokenExpiresInSeconds: 0,
      silentRenew: false,
      
      logLevel: LogLevel.Debug,
      historyCleanupOff: true,
      
    });
}

```
**After logout**
![image](https://user-images.githubusercontent.com/45000952/110319077-57dcfb00-8049-11eb-9797-db23a3bd043e.png)

After clicking the link, it is redirecting to logout but display dashboard again. Console log is below
![image](https://user-images.githubusercontent.com/45000952/110319580-10a33a00-804a-11eb-85ca-a76a97a49c71.png)

**Comment by FabianGosebrink** [comment] 2021-03-08 13:31
Hey, check your app.component's code and see the examples. This should fix it. If not please prove a sample repo and then we can have a look. Thanks.

**Comment by ebinroy** [comment] 2021-03-09 12:09
Hi , I checked your source code and noticed that if I remove AutoLoginGuard from home there is an issue. 

![image](https://user-images.githubusercontent.com/45000952/110463117-75bf6400-810c-11eb-9977-3c8c27b07ccd.png)

Home page
![image](https://user-images.githubusercontent.com/45000952/110463215-95ef2300-810c-11eb-8b3d-0de804716422.png)
![image](https://user-images.githubusercontent.com/45000952/110463347-c46cfe00-810c-11eb-9619-9664b15c1880.png)

if I go http://localhost:4200/protected -->  redirect to STS --> redirect to Home page again
![image](https://user-images.githubusercontent.com/45000952/110463464-e6668080-810c-11eb-90d2-18dada8389ec.png)

I have uploaded my source code to this [**repository**](https://github.com/ebinroy/AngularOidc) and the facing issues are below

**Scenario1** : if dashboard route has canActivate: [AutoLoginGuard]

Issue 1:-  , redirect to logout not working. Actually its redirecting to logout page and then redirect to STS to login

issue 2:- user not login to STS, clicking link http://localhost:4300/secureddetails  will redirect to STS , after login redirect to http://localhost:4300    instead of secureddetails. if I want to redirect to the entered path what shd I do?

**Scenario 2** : if dashboard route has REMOVE  canActivate: [AutoLoginGuard] 

issue3:- I am getting userData$ as null in app.component.ts and I can not view secureddetails page redirecting to the dashboard always.
![image](https://user-images.githubusercontent.com/45000952/110468276-08fb9800-8113-11eb-9bb9-350d6806f785.png)

**Comment by damienbod** [comment] 2021-03-12 12:12
@FabianGosebrink @ebinroy 

Can we close this?

Greetings Damien

**Comment by ebinroy** [comment] 2021-03-14 15:15
@FabianGosebrink @damienbod   I have upload the  source on the above command to prove the issue. Can you take a look on this. Thanks

**Comment by FabianGosebrink** [comment] 2021-03-14 15:21
In your repository add the `checkAuth()` call to your app component. See the docs (here)[https://github.com/damienbod/angular-auth-oidc-client/blob/main/docs/features.md#auto-login]

**Comment by ebinroy** [comment] 2021-03-15 08:22
@FabianGosebrink  @damienbod 

I worked on the sample and everything is working fine. But when it applied on my source code the redirection is not working

Source code you can find here --> [AngularOidc](https://github.com/ebinroy/AngularOidc)

The problem is redirect URL not working. 

**Scenario1**

1.  Enter the URL http://localhost:4200/#/secureddetails
2. Redirect to STS for login
3. After login redirect to dashboard page 

**Scenario2**
1. Click Logout
2. Not redirecting to logout page instead dashboard page is displayed

Both cases some issue with redirect I could not found the issue. **Can you please help me to find the issue**. Thanks

**Comment by FabianGosebrink** [comment] 2021-03-15 08:54
Please update to the latest version in your `package.json` and try again. Just tried it out and it works on my site.

`"angular-auth-oidc-client": "^11.6.1",` ---> `"angular-auth-oidc-client": "^11.6.4",`

Please let us know if this helped.

Thanks

**Comment by ebinroy** [comment] 2021-03-15 08:58
@FabianGosebrink @damienbod 

Actually I used 11.6.1 for the sample source and redirect login and logout don't have any issue. I don't think version is the issue.

**Comment by FabianGosebrink** [comment] 2021-03-15 09:03
I just forked your repo and could reproduce the issue you mentioned. I personally fixed the issue in this https://github.com/damienbod/angular-auth-oidc-client/pull/1015 which was released in the mentioned version 11.6.4. https://github.com/damienbod/angular-auth-oidc-client/blob/main/CHANGELOG.md.

Please update to the latest version and tell us if the issue still exists.

**Comment by ebinroy** [comment] 2021-03-15 09:11
Yes Noted. The first scenario is solved. The second scenario about redirect log out is not working

**Scenario2**

1. Click Logout
2. Not redirecting to logout page instead dashboard page is displayed

**Comment by FabianGosebrink** [comment] 2021-03-15 09:19
Have you configured your sts correctly to redirect to `<your-domain>/logout` instead of only `<your-domain>`? It lands on dashboard because you redirect to `<your-domain>`. CLient looks good, looks like a server issue to me.

**Comment by ebinroy** [comment] 2021-03-15 09:32
Yes. STS side logout URL configured correctly only. You can check the log. It is redirect from STS to logout and again redirect to the dashboard.

![image](https://user-images.githubusercontent.com/45000952/111132385-413c2400-85b4-11eb-9530-a70ec8f82d81.png)

**Comment by FabianGosebrink** [comment] 2021-03-15 09:37
Yes, you have ` {provide: LocationStrategy, useClass: HashLocationStrategy},` turned on. This logout/redirect issue can be reproduced easily when you type in `http://localhost:4200/login` and hit Enter, you are getting redirected to the dashboard. Have you tried redirecting to the `logout` with a "hash" --> `/#/logout`?

**Comment by ebinroy** [comment] 2021-03-15 09:37
OOps sorry its my mistake! Its working. Thanks for fixing the package! All the best

**Comment by FabianGosebrink** [comment] 2021-03-15 09:37
Maybe you can tell us and other what you did to fix the issue. Thanks!

**Closed** 2021-03-15 09:37 UTC
Labels: question

**Comment by ebinroy** [comment] 2021-03-15 09:41
Actually your finding has the answer that why I did not mentioned. I have turned on HashLocationStrategy because of that URL has a hash that I have not provided in postLogoutRedirectUri. So the correct redirection works as below.

postLogoutRedirectUri: `${window.location.origin}/#/logout`,

**Comment by FabianGosebrink** [comment] 2021-03-15 09:45
Perfect, thanks for letting us know!
