### ISSUE TITLE
Redirect after sign-in breaks with query parameters

### ISSUE THREAD

**Issue by CobusKruger** [damienbod/angular-auth-oidc-client#1042] opened 2021-04-12 16:36 UTC
**Describe the bug**
I previously had custom code to pick up the `redirect` entry from storage and navigate to it. When I upgraded to 11.6.4, I had to take it out, because of the `navigate()` call on this line:
https://github.com/damienbod/angular-auth-oidc-client/blob/630f4e7f4eb92e432e540b739d2034e52b0e027b/projects/angular-auth-oidc-client/src/lib/check-auth.service.ts#L79

```
// in check-auth.service.ts, checkAuth function:
      tap(() => {
        const savedRouteForRedirect = this.autoLoginService.getStoredRedirectRoute();
        if (savedRouteForRedirect) {
          this.autoLoginService.deleteStoredRedirectRoute(); // This removes the entry
          this.router.navigate([savedRouteForRedirect]);         // This navigates and causes the error
        }
      }),
```

My own navigation failed (as expected) because the `redirect` entry no longer exists by the time my code executed.

The new problem is that if the `redirect` entry contains any path with query parameters, navigation will fail. That's because `navigate()` doesn't support query parameters as part of the commands array. Suppose I have a URL like `/?p=1`, I will receive the following error:

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'p%3D1'
```

Changing that line to the following should work:

```
          this.router.navigateByUrl(savedRouteForRedirect); // Supports query parameters
```

**To Reproduce**
1. Have an app with authentication enabled.
2. Paste a URL **without** query parameters into the browser address bar and press Enter. This goes through the login flow, then routes to the supplied path. **Expected**
3. Paste a URL **with** query parameters into the browser address bar and press Enter. This goes through the login flow, then throws an error to say `Cannot match any routes`. **Not expected**

**Expected behavior**
Navigate to the redirect URL, whether it has query parameters or not.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrom
 - Version: 89.0.4389.114

I'll be happy to make the change.

**Comment by FabianGosebrink** [comment] 2021-04-12 17:43
Hey, thanks for this. Did you try if the error is gone when you work with the [QueryParamsHandling](https://angular.io/api/router/QueryParamsHandling)?

**Comment by CobusKruger** [comment] 2021-04-12 18:04
I don't know what that is, but I'll investigate it.

**Comment by FabianGosebrink** [comment] 2021-04-12 19:10
You can configure how Angular handles the queryParams. So maybe this solves the issue. You can test it and please let us know. Thanks!

**Comment by CobusKruger** [comment] 2021-04-13 07:28
@FabianGosebrink I looked into `QueryParamsHandling`, and I can't see how that helps in my case. Setting it to `merge` or `preserve` gets the router to pass them on, but we're going through Azure AD authentication. More than that, it's passed as a parameter to `navigate()`, and I don't see a way to set it globally.

**Comment by FabianGosebrink** [comment] 2021-04-22 17:57
Could be fixed by https://github.com/damienbod/angular-auth-oidc-client/pull/1051 which is released. Please check and close if the issue is solved.

**Comment by inloox-dev** [comment] 2021-04-22 17:59
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25247 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] Redirect after sign-in breaks with query parameters (#1042)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25247>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________

**Closed** 2021-06-11 22:10 UTC
Labels: question
