### ISSUE TITLE
Azure B2C

### ISSUE THREAD

**Issue by tcrite** [damienbod/angular-auth-oidc-client#74] opened 2017-09-02 03:07 UTC
Hi,

Just wondering if this can work with Azure B2C?

**Comment by damienbod** [comment] 2017-09-02 04:47
yes

https://github.com/HWouters/ad-b2c-oidc-angular

Greetings Damien

**Comment by damienbod** [comment] 2017-09-02 05:09
Here's an working example until the PR is merged

https://github.com/damienbod/ad-b2c-oidc-angular

**Comment by tcrite** [comment] 2017-09-02 14:43
Awesome. And thanks for the fast response!

**Closed** 2017-09-03 05:47 UTC

**Comment by mhadji** [comment] 2018-06-07 15:51
Hi ,
I am using Angular 6 and Ad B2C. I see the response back from B2C in URL but it doesn't make its way to session storage.Is it any issue with angular 6?

**Comment by damienbod** [comment] 2018-06-07 18:06
@mhadji I'll look, this is the second time someone reported this.

**Comment by mhadji** [comment] 2018-06-07 18:15
I found the solution in https://stackoverflow.com/questions/49220150/no-state-in-response-after-callback-in-oidc-client-js and it worked for me .


It is caused by URI encoding of state in the window.location.hash. For me this fix the issue:

if (window.location.hash) {
window.location.hash = decodeURIComponent(window.location.hash);
// authorizedCallback returns wrong result when hash is URI encoded
this.oidcSecurityService.authorizedCallback();
} else {
this.oidcSecurityService.authorize();
}

**Comment by damienbod** [comment] 2018-06-07 19:49
@mhadji thanks for the feedback.
