### ISSUE TITLE
Check session always checked locally.

### ISSUE THREAD

**Issue by Expelz** [damienbod/angular-auth-oidc-client#756] opened 2020-05-22 13:35 UTC
Hello.
In the recursive function doesn't include call to CheckSessionService.init() :

https://github.com/damienbod/angular-auth-oidc-client/blob/ea4e382b2607205297650523b96874a88e278bed/projects/angular-auth-oidc-client/src/lib/iframe/check-session.service.ts#L94-L120

This causes the check session logic to malfunction because the session state check always takes place locally.
Are there any reasons why you don't invoke init() inside pollServerSessionRecur() function as it was in previous version?

And also it would be very convenient to be able to configure these variables:
https://github.com/damienbod/angular-auth-oidc-client/blob/ea4e382b2607205297650523b96874a88e278bed/projects/angular-auth-oidc-client/src/lib/iframe/check-session.service.ts#L20-L21

**Comment by damienbod** [comment] 2020-05-29 16:50
Hi @Expelz  @valdian Can you help me a bit here, what is the problem here (sorry if I don't understand)? How can I reproduce the problem? I have tested the checkSession and this works for me (The way I test it, but I assume you use it different, so I probably missed something)

Greetings and thanks Damien

**Comment by valdian** [comment] 2020-05-29 22:22
@damienbod Check session works, but the regular refresh is missing. 

In the previous versions, the check session iframe used to be refreshed every minute. When I use version 10 and open my app in a browser, I can see also in the network tab of development tools that the checksession endpoint is called every minute. With version 11, the checksession endpoint is called only once in the beginning.

The regular refresh was introduced in #314. See the issue discussion for the reasons behind.

But the refresh disappeared in commit 1750ee2. The question is: Was it done by accident or was it an intention? It looks like done by accident because the field `iframeRefreshInterval` is still present in the CheckSessionService.

**Comment by damienbod** [comment] 2020-05-30 07:40
@valdian Thanks for the info. Let's get the PR merged then , maybe @FabianGosebrink can help you with the tests?

**Closed** 2020-05-30 08:08 UTC
Labels: investigate

**Comment by Expelz** [comment] 2020-05-30 09:27
@valdian thank you for contributing! #761 will solve this issue.

@damienbod @FabianGosebrink guys you do a great job. Thank you!
