### ISSUE TITLE
[Firefox] ValidateStateFromHashCallback failed, state: {someVal} local_state:null

### ISSUE THREAD

**Issue by abdunnahid** [damienbod/angular-auth-oidc-client#920] opened 2020-12-20 10:38 UTC
I have a similar issue like [#195](https://github.com/damienbod/angular-auth-oidc-client/issues/195), [#545](https://github.com/damienbod/angular-auth-oidc-client/issues/545) except it happens only on a fresh Firefox with all the browser storage cleared and the console says,

`ValidateStateFromHashCallback failed, state: {someVal} local_state:null`

**Note:** On a private instance, it is not reproducible!

I am using the latest **v11.2.4**. I got the right token from Azure B2C but for some reason I get the console message mentioned above and it redirects to _/unauthorized_. The same thing works on Chrome perfectly fine.

**Desktop:**
 - OS: Windows, MacOS
 - Browser: Firefox
 - Version: 84.0

**Comment by vicky-singh** [comment] 2021-01-09 22:21
@damienbod may be related to #936

**Comment by valdian** [comment] 2021-02-02 22:39
Hi, I do not know your code, so it is hard to guess what happens behind the scenes. But it reminds me of one similar (or maybe the same) issue I faced a few months ago.

The `state` value is generated before a redirect to the OIDC server. It is stored in the browser storage (localStorage in my case) so that it can be retrieved after the redirect back to the angular app. Your error can occur when it is not found there. I saw this behaviour in Firefox, when "Delete cookies and site data when Firefox is closed" setting was enabled. Under these circumstances, the localStorage was not preserved after redirects within the same tab.

But I also observed, that when I was already logged-in in the OIDC server before authentication in the angular app, the localStorage was not cleared and the authentication process succeeded.

So I used this workaround:
```ts
this.oidcSecurityService.checkAuth().subscribe((isAuthenticated) => {
  // if the callback fails
  if (window.location.pathname === '/callback' && !isAuthenticated) {
    // because the state value is not found in the browser storage
    if (!oidcSecurityService.getState()) {
      // then initiate the authentication process again
      this.oidcSecurityService.authorize();
    }
  }
});
```
Could you maybe try it? If it does not help or my idea is not clear to you, please share more details (config, code), and I can investigate it further.

**Comment by damienbod** [comment] 2021-02-27 17:57
closing this as I cannot reproduce or solve. Please open if this has been closed incorrectly.

Greetings Damien

**Closed by damienbod** 2021-02-27 17:57 UTC
Labels: investigate

**Comment by silviu-negoita** [comment] 2021-11-15 13:57
Hello. Im facing a similar issue, but i think i know how to reproduce it.
My scenario:
1.  using default session storage
2. Login -> oidc server redirects me back to SPA
3. I have an http interceptor where i check `oidcSecurityService.isAuthenticated$` to add the token on request. Mentioning that this call is done **before** `oidcSecurityService.checkAuth()`. 
4. Run in the same issue as the OP

Workaround: 
If I replace `oidcSecurityService.isAuthenticated$` with the check `oidcSecurityService.getAccessToken() != null` I fix the issue. 

Might be the fact that `isAuthenticated$` is resetting the state when it is called before `oidcSecurityService.checkAuth()` ?
