### ISSUE TITLE
Using silent_renew url, when clicking authorize

### ISSUE THREAD

**Issue by GabrielGil** [damienbod/angular-auth-oidc-client#788] opened 2020-06-11 15:46 UTC
**Describe the bug**
Some logins seem to be performed incorrectly on the first attempt, maybe due stale state. Trying to login a second time, works fine.

This happens after a silent renew was incomplete, maybe because internet is disconnected. The next call to `/token` uses the silent renew redirect url, not being a silent renew auth, but a regular `authorize()` call.

```
OidcService code request https://id.octavo.app with error [object Object]
```

**To Reproduce**
1. Login in the app
2. Wait for access token to expire
3. Login again. The redirect route containing `?code=whatever` will throw the error. The login wasn't performed.
4. Log in one last time. This time, the received token works without problems.

**Expected behavior**
The `authorize()` call should not include the silent renew redirect url.

**Screenshots**
![image](https://user-images.githubusercontent.com/961534/84407201-d025a580-ac0a-11ea-9c30-18d385ed9000.png)

![image](https://user-images.githubusercontent.com/961534/84407458-2eeb1f00-ac0b-11ea-90cb-92523da7c8d2.png)

![image](https://user-images.githubusercontent.com/961534/84407546-4924fd00-ac0b-11ea-9fdf-a69c1c9e0cd9.png)

**Desktop :**
 - OS: Mac, Windows
 - Browser Chrome, Edge, Firefox
 - Version Latests

**Smartphone (please complete the following information):**
 - Device: Pixel 3, iPhone X
 - OS: Mac, Windows
 - Browser Chrome, Edge, Firefox
 - Version Latests

**Additional context**

**Comment by Expelz** [comment] 2020-06-12 15:53
Hi @GabrielGil!
What version of the library are you using?

**Comment by GabrielGil** [comment] 2020-06-12 16:47
Hey @Expelz, thanks for the interest. I am using version 11.1.3 currently.

**Comment by Expelz** [comment] 2020-06-15 19:24
@GabrielGil Can you please share your oidc-client configuration? Need more context to investigate your issue.

**Comment by GabrielGil** [comment] 2020-06-16 10:00
Hi @Expelz, this is how we configure our `CoreModule`.

Note that `disableIatOffsetValidation` is true because I was receiving errors from users which apparently had their time settings correctly set, but there was an error coming up saying the token was issued too far away, but it wasn't. I still gotta investigate that.

Also, it is possible for you to check the live app at https://octavo.app if that helps anyhow.

```ts
export function configureAuth(oidcConfigService: OidcConfigService) {
  return () =>
    oidcConfigService.withConfig({
      stsServer: 'https://id.octavo.app',
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
      clientId: 'octavo',
      scope: 'openid profile email',
      responseType: 'code',
      silentRenew: true,
      silentRenewUrl: `${window.location.origin}/silent-renew.html`,
      logLevel: LogLevel.Warn,
      disableIatOffsetValidation: true,
    });
}

@NgModule({
  imports: [
    AuthModule.forRoot(),
    GraphQLModule,
    HttpClientModule,
  ],
  providers: [
    OidcConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: configureAuth,
      deps: [OidcConfigService],
      multi: true,
    },
  ],
})
export class CoreModule {}
```

Thanks,
Gabriel.

**Comment by Expelz** [comment] 2020-06-16 19:20
Hi @GabrielGil, thanks for sharing oidc configuration.

I guess the problem is in your IS configuration. As you can see from this request:
![image](https://user-images.githubusercontent.com/33082852/84815148-46ffdb80-b01b-11ea-8dd8-0223d01d9806.png)

This redirect url `https://...../silent-renew.html` can be set only by the silent renew process (and it's expected behavior). Such error response `invalid_grant` mean that inside your IS configuration for this client `https://octavo.app/` you didn't include this redirect url `https://...../silent-renew.html`.

**Please note** that silent renew process also do call to /token endpoint only with different redirect url because it should done "silent token renew" for user inside hidden `iframe`.

To solve this problem simply update your IS configuration:
```
RedirectUris =  { "https://octavo.app", "https://octavo.app/silent-renew.html" },
```
It should solve the problem.


> The authorize() call should not include the silent renew redirect url.

If you directly call `authorize()` function it will always do direct redirect to IS url which you set inside `withConfig()` function.

Let me know if you still have some issues with it.

**Comment by GabrielGil** [comment] 2020-06-16 19:37
Hi @Expelz. Thanks for your clarification. In this case, I didn't miss to add the silent renew url in the configuration of the IS. Indeed, the silent renew works fine most of the time. For instance, when opening a new tab (if previously logged in) the silent renew process, and the app calls the token endpoint with a code and the silent renew URL as you can see in this screenshot and as it can be checked in the live app, if you will.

![image](https://user-images.githubusercontent.com/961534/84820109-6433aa80-b019-11ea-9b0a-3d486646676b.png)

Please, let me know if I am missing any bit, or is there anything I can do to help debug this further.

**Comment by Expelz** [comment] 2020-06-16 20:03
Can you provide more information about this reproduce steps:

> 2. Wait for access token to expire
As I could see from your configuration you don't use `startCheckSession`. Do you have some code which handle token expiration?
> 3. Login again. The redirect route containing ?code=whatever will throw the error. The login wasn't performed.
Can you give some details how you do this re-login?

**Comment by GabrielGil** [comment] 2020-06-24 11:23
Hey, sure. I missed this one.

The token expires and it wasn't correctly renewed due connectivity issues (unreliable connection on mobile networks).

I don't use `startCheckSession` as I am not certain of what that does, to be honest. Your explanation would be appreciated. We don't have any code to handle token expiration.

**Comment by michaelmarcuccio** [comment] 2020-10-12 04:26
I have this same bug. As soon as the refresh_token is invalid, and the auto refresh triggers(I am using non iframe version) then this occurs. I have not found a way to handle the error and redirect to login page, nor a hook to subscribe to this event in the first place.
![image](https://user-images.githubusercontent.com/20432260/95705248-f12def80-0c18-11eb-826d-715c047b9c62.png)

**Comment by spodgaysky** [comment] 2020-12-14 09:48
Hi, guys. Do you have any updates on it?
I faced the same problem as Gabriel. 
Console logs and network errors are the same as was described.

**My auth config:**
`export const authConfig: OpenIdConfiguration = {
  stsServer: environment.baseUrl,
  redirectUrl: window.location.origin,
  postLogoutRedirectUri: window.location.origin,
  clientId: 'web.admin',
  scope: 'openid profile email api',
  responseType: 'code',
  silentRenew: true,
  silentRenewUrl: `${window.location.origin}/silent-renew.html`,
  renewTimeBeforeTokenExpiresInSeconds: 15,
  renewUserInfoAfterTokenRenew: true,
  triggerAuthorizationResultEvent: true
}`

**My steps to reproduce the issue**:
1. Login in the app
2. Stop angular app and don't close browser tab (wait for silent-renew script to work at least once - since we are on the same tab, silent renew still works on the background)
3. Start angular app
4. Refresh the page

**Note**: when following the steps mentioned above, but opening app in the new tab instead of accessing previous one, there are no such errors

**Comment by damienbod** [comment] 2021-02-07 22:48
this should be fixed now with the new silent renew protection check.

**Closed by damienbod** 2021-02-07 22:48 UTC
Labels: investigate
