### ISSUE TITLE
Problem when using interceptors which depend on module "setup"

### ISSUE THREAD

**Issue by ngRevan** [damienbod/angular-auth-oidc-client#1191] opened 2021-07-14 06:27 UTC
**Describe the bug**
I have a problem when using interceptors which depend on the setup of another module. In my case I use @ngrx/store and select values from the store in the interceptor. If I understand correctly, the StsConfigLoader is executed during registration rather than during app initialization which leads to the state still being undefined. I'm aware that this is quite a unique case but I think this could generally lead to "race conditions" with other module setup actions.

**To Reproduce**
I have created a [Stackblitz](https://stackblitz.com/edit/ngrx-app-initializer-sample?file=src/app/app.module.ts) which showcases the issue.

The exception can be triggered by changing the lines in `testLoaderFactory` in the AppModule.
```
export function testLoaderFactory(loader: Loader) {
  // Exception (state not present)
  // const allLoadPromises = loader.load();
  // return () => allLoadPromises;

  // No Exception (state present)
  return () => loader.load();
}
```

**Expected behavior**
Config should be loaded during app initialization when other modules have completed "registration".

I think the issue would be fixed by changing the configurationProviderFactory to the following:
```ts
export function configurationProviderFactory(oidcConfigService: OidcConfigService, loader: StsConfigLoader) {
  return (): Promise<OpenIdConfiguration[]> => {
    return Promise.all(loader.loadConfigs()).then((configs) => oidcConfigService.withConfigs(configs));
  };
}
```

Would that be possible or is there any reason not to?
I could submit a PR if that helps.

Thanks a lot for your work!

**Comment by FabianGosebrink** [comment] 2021-12-14 06:51
We are about to remove the app initializer completely with https://github.com/damienbod/angular-auth-oidc-client/pull/1307. I hope the issue is fixed then.

**Comment by FabianGosebrink** [comment] 2022-02-19 17:12
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Closed by FabianGosebrink** 2022-02-19 17:12 UTC
Labels: investigate
