### ISSUE TITLE
Tokens are missing after calling the refresh token

### ISSUE THREAD

**Issue by ZsomborTihanyi** [damienbod/angular-auth-oidc-client#1190] opened 2021-07-13 15:58 UTC
Hi!

I'm using v12.0.1 with Angular 12.1.1. I'd like to authenticate with code flow PKCE & refresh tokens.
My config is as follows:

```
imports: [AuthModule.forRoot({
        config:{
            authority: 'http://127.0.0.1:8080/c2id',
            redirectUrl: 'http://127.0.0.1:4200/login',
            postLogoutRedirectUri: 'http://127.0.0.1:4200/login',
            clientId: 'aowukh7pllgme',
            scope: 'openid profile address email certificate',
            responseType: 'code',
            silentRenew: true,
            useRefreshToken: true,
            logLevel: LogLevel.Debug,
        }
      })
    ],
```

On the server side, the refresh token has no expiry and the accsess token lifetime is set to 30 sec.
When that time is up, the new access token appears in the console, but after that, the refresh token no longer exists and the value of the access-, refresh- and id token are already null.

![image](https://user-images.githubusercontent.com/43534434/125484961-83511250-649d-4cd3-a4ba-0bc5a821b4bf.png)

Maybe it's a configuration failure, or something else?

Thanks!

**Comment by FabianGosebrink** [comment] 2021-07-13 16:02
Not sure but try to add the `offline_access` in the scopes as well.

**Comment by ZsomborTihanyi** [comment] 2021-07-13 17:02
Thanks for the reply, I tried but unfortunately, still have the same problem.

**Comment by FabianGosebrink** [comment] 2021-07-13 18:19
Maybe @damienbod can help when he is back from his holiday :)

**Comment by damienbod** [comment] 2021-07-15 08:57
Hi  @ZsomborTihanyi This looks like your IDP does not return the id_token. What IDP do you use. You can disable the id_token check but when using refresh tokens, you should use refresh token rotation and the revocation endpoint. 

Greetings Damien

**Comment by ZsomborTihanyi** [comment] 2021-07-19 16:24
Thank you for your answer!

I use the [c2id](https://connect2id.com/products/server/docs/api) as a sts server, but ​don't found the opportunity to set the token rotation endpoint yet.

**Comment by damienbod** [comment] 2021-07-25 09:27
Would it be possible to setup a test IDP which we can test against?

Greetings Damien

**Comment by ZsomborTihanyi** [comment] 2021-07-27 12:18
Sure (and sorry for the delay)!

We using the c2id server with the same configuration:
https://drive.google.com/file/d/1rW7J0vPSGxmyrBDRo57MRecMERgC001D/view?usp=sharing

Server start/stop: tomcat/bin/startup.sh / tomcat/bin/shutdown.sh
The access-refresh token default lifetime can be changed in: tomcat/webapps/c2id/WEB-INF/authzStore.properties

The registered client:
```
{
"grant_types": [
  "refresh_token",
  "authorization_code"
],
"subject_type": "public",
"application_type": "web",
"registration_client_uri": "http://127.0.0.1:8080/c2id/clients/aowukh7pllgme",
"redirect_uris": [
  "http://127.0.0.1:4200/login"
],
"client_id_issued_at": 1625841077,
"registration_access_token": "3hR1RO7aVq5x-CTaJI6ESmbBVy8QMHnUi8uLmnIgA1I.YSxpLHIscCxjLGoscyxzY3Asc3VybixpZCxzZWMsZA",
"token_endpoint_auth_method": "none",
"client_id": "aowukh7pllgme",
"response_types": [
  "code"
],
"id_token_signed_response_alg": "RS256"
}
```

C2id contains pre registerered ldap users (user in use: alice).

I hope it helps to reproduct the problem!

**Comment by kewur** [comment] 2021-08-01 05:41
I have the same issue with cognito. on the first expiration I am able to get tokens just fine. But the one after that I have an error log saying "no refreshtoken found, please login"

**Comment by damienbod** [comment] 2021-08-02 06:06
Refresh tokens should only be used in the browser if the extra mitigations required for refresh tokens are supported from the IDP. One time token usage, refresh token rotation are important, revocation as well. Refresh token without this might not be the best choice to secure your application if the IDP does not support this. Maybe if the IDPs cannot be updated for using refresh tokens in the browser, consider a server rendered application (BFF) or revert to iframes. None are perfect.

If the id_token is missing after a refresh, then I will add support for this, fix this. If the refresh token is not rotated, this cannot be fixed.

Greetings Damien

**Comment by kewur** [comment] 2021-08-02 14:33
I see, so you're saying cognito doesn't send a refreshtoken together with the request? Is there a debug option to see if my IDP is returning a new refresh token or not? and if it isn't would using "forceRefreshSession" allow me to get new ones? 

Excuse my ignorant questions but, my login screen is a hosted UI, would that count as an iframe?

**Comment by ZsomborTihanyi** [comment] 2021-08-02 14:36
Thank you!

I think the refresh token rotation supported from the IDP, because the c2id server config includes the following option to set this value:

```
# If true causes the refresh token to be updated (rotated) on each
# authorisation update and on each refresh token use. Applies to long-lived
# authorisations only, the refresh tokens for short-lived (transient)
# authorisations are not affected. The default value is false (no update).
authzStore.refreshToken.alwaysUpdate=true
```
In this case, the refresh token at the authorization and after 30 sec, is different.

However, after we got the second accsess/refresh token pair, the tokens already missing:
![image](https://user-images.githubusercontent.com/43534434/127878503-fa7044db-4751-465a-84ad-e8340b3a453c.png)

**Comment by Vijay-Tummala** [comment] 2021-09-03 03:32
I have same issue on 12.0.3. The refresh token is cleared after signle refresh.

It throws below error:

- no refresh token found, please login
- silent renew failed! no refresh token found, please login

**Comment by FabianGosebrink** [comment] 2021-09-03 06:32
Can you reproduce this with one of our samples?

**Comment by Vijay-Tummala** [comment] 2021-09-03 17:27
@FabianGosebrink 

Thank you for building such a resouceful library.

I reproduced the issue with one of the samples. We are using our local sts server with token lifetime set as 30 seconds.

Sample: "sample-code-flow-http-config"

Config: 

![image](https://user-images.githubusercontent.com/16924807/132043840-de59eb3c-1af3-45ef-80de-710224b046f5.png)

Output Console:

First Referesh:

![image](https://user-images.githubusercontent.com/16924807/132044111-5a5d0c45-d555-4c21-9a04-3da74c30e742.png)

Second Refresh:

![image](https://user-images.githubusercontent.com/16924807/132044144-494b9e64-68d8-4cc6-a094-51992b9630fb.png)


I observed that sts response after first refresh doesn't have a refresh token (This is expected as refresh_token request doesn't return a return a refresh_token itself). I beleieve the refresh token is overriden with null after this.

**Comment by damienbod** [comment] 2021-09-03 17:45
We have implemented refresh tokens so that the tokens can only be used once in browser as recommended for browsers. Using refresh tokens in the browser which can be used more than once is not recommended and not a good idea. If your IDP does not support refresh tokens one time usage, then you should not use refresh tokens in the browser. Consider changing your IDP or use a different authentication flow, renew.

Greetings Damien

**Comment by Vijay-Tummala** [comment] 2021-09-03 17:50
@damienbod 

Thanks for the clarification.

**Comment by FabianGosebrink** [comment] 2021-09-19 14:09
Closing as there hasn't been any response from the issue author. Please re-open if you are still seeing problems here.

**Closed by FabianGosebrink** 2021-09-19 14:09 UTC
Labels: question, More information needed, no_id_token_returned_refresh_flow
