### ISSUE TITLE
Does the current library (v 16.01) work with Angular 17? 

### ISSUE THREAD

**Issue by silviu-sterian** [damienbod/angular-auth-oidc-client#1893] opened 2024-02-01 15:57 UTC
16.1

Someone from our team tried to upgrade and reported it was not compatible.
Any scheduled version updates?

**Comment by damienbod** [comment] 2024-02-01 16:27
We willl release a .NET 17 version, just waiting for the strict PR

Greetings Damien

**Comment by G-Kumaran** [comment] 2024-02-02 17:28
On angular 17, installation fails on schematics with

> Could not find the project main file inside of the workspace config (src)

Most likely due to the missing appmodule

**Comment by timdeschryver** [comment] 2024-02-02 17:30
> On angular 17, installation fails on schematics with
> 
> > Could not find the project main file inside of the workspace config (src)
> 
> Most likely due to the missing appmodule

This will be resolved with the new version.
The `buildOptions` within the `angular.json` were changed, and is the cause of the error.

**Comment by damienbod** [comment] 2024-02-02 19:54
I will release this tomorrow, without the strict PR

Greetings Damien

**Comment by silviu-sterian** [comment] 2024-02-02 19:56
Thank you Damien! That's really good news!

**Closed** 2024-02-04 12:26 UTC
Labels: question
