### ISSUE TITLE
Should 5 seconds timeout on silent_renew be configurable? => fails fast now if server responds

### ISSUE THREAD

**Issue by SolarMaximus** [damienbod/angular-auth-oidc-client#357] opened 2018-12-07 16:55 UTC
Hello. I have one issue with 5 seconds silent_renew timeout. I have an angular 6 application with implicit flow, long-living session on Identity Server 4 and short-living access tokens. Silent_renew is enabled. When I come to any of private pages, I want to be instantly logged in to my application if session is up or redirected to my login page otherwise, but I have to wait 5 seconds because my AuthGuard is subscribed to _oidcSecurityService.getIsAuthorized(). I think it would be nice if timeout could be set as parameter. Maybe someone can propose a better solution.

**Comment by profet23** [comment] 2018-12-07 22:12
It should be instant. If it's not instant, then your silent_renew isn't configured properly (maybe a CORS issue?) or your auth server is down. The 5 second timeout is a fail safe for when the server fails to respond to the silent renew.

Could you try turning on logging and looking at the console for any errors?

**Comment by SolarMaximus** [comment] 2018-12-10 08:45
Silent renew works properly if user has already been authenticated in my angular application. But I try to implement SSO. I have one application with AuthorizationCode flow and I login through it and create session in my identity provider. After this I try to visit private page of my angular app. 

![image](https://user-images.githubusercontent.com/29251904/49720261-62dd3100-fc70-11e8-9122-4f1fa331fee4.png)

After timeout it successfully calls authorized callback and everything is fine. 

![image](https://user-images.githubusercontent.com/29251904/49720389-b0599e00-fc70-11e8-89f8-861b6d229768.png)

**Comment by Fallarch** [comment] 2018-12-10 13:14
We have same problem in our application as @SolarMaximus . Before redirecting to our unauthorized page, there is 5s timeout(either before login and after logout). We noticed, that this behavior started, when we upgraded angular-auth-oidc-client from version 6.x.x to 8.0.3(in version 6.x.x there is no timeout).

**Comment by SolarMaximus** [comment] 2018-12-10 13:19
In 8.0.3 there was a change which switched default silent_renew value from true to false. But I have this issue when it is enabled. In 6.0.* version and in 8.0.3.

**Comment by Fallarch** [comment] 2018-12-10 13:46
@SolarMaximus We had it enabled in version 6.0.x too.

**Comment by profet23** [comment] 2018-12-10 18:34
@SolarMaximus @damienbod  Looking at the provided console output:

![Provided Imaged](https://user-images.githubusercontent.com/29251904/49720261-62dd3100-fc70-11e8-9122-4f1fa331fee4.png)

It shows that `refreshSession()` is never being called because the authNonce has been previously set.

@SolarMaximus  could you try in an incognito window and see if the timeout is hit? (My guess is that it is not).

Maybe the authNonce needs to be cleared on storage init?

**Comment by SolarMaximus** [comment] 2018-12-11 11:17
@profet23 Timeout still hits. Tried to clear authNonce from localStorage before calling

openIDImplicitFlowConfiguration.storage = localStorage;
this.oidcSecurityService.setupModule(openIDImplicitFlowConfiguration, authWellKnownEndpoints);

but it causes infinite recursion with refreshSession, because authNonce is always null.

**Comment by profet23** [comment] 2018-12-11 14:16
The timeout hits even when using an incognito window?  Hrm...   You may have an order of operations issue. What are you doing before subscribing to `getIsAuthorized()`?

**Comment by profet23** [comment] 2018-12-11 14:18
Before this change, getIsAuthorized() would not attempt authorization before returning false. So you would have to wait by some mechanism until the library received an authorization event before checking it.

**Comment by SolarMaximus** [comment] 2018-12-12 07:55
`@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

  constructor(private _router: Router,
              private _authService: AuthService) {
  }

  public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
    // console.log(route + '' + state);
    // console.log('AuthGuardService, canActivate');

    return this._authService.getIsAuthorized().pipe(
      map((isAuthorized: boolean) => {
        // console.log('AuthGuardService, canActivate isAuthorized: ' + isAuthorized);

        if (isAuthorized) {
          return true;
        }
        localStorage.setItem('backUrlAfterLogin', state.url);
        this._router.navigate(['/login']);
        return false;
      })
    );
  }
}`

`@Injectable({
  providedIn: 'root'
})
export class AuthService {

  public isAuthorized: boolean;
  public currentUser: User;
  public userLoggedIn = new Subject();

  constructor(private _oidcSecurityService: OidcSecurityService,
              private _alertService: AlertService,
              private _router: Router) {
    this.isAuthorized = false;

    this._oidcSecurityService.getIsAuthorized()
      .subscribe(isAuthorized => {
        this.isAuthorized = isAuthorized;
        if (isAuthorized) {
          this.userLoggedIn.next();
          this._alertService.success('You are logged in');
          this._oidcSecurityService.getUserData().subscribe(userData => {
            this.currentUser = new User(
              userData.sub,
              userData.preferred_username,
              userData.given_name,
              userData.family_name,
              userData.email,
              userData.email_verified,
              Array.isArray(userData.permission) ? userData.permission : [userData.permission],
              userData['employee-identifier']
            );
            // console.log('authService.currentUser:' + JSON.stringify(this.currentUser));
            // console.log('authService.jwtToken:' + JSON.stringify(this.getToken()));
          });
        }
      });
  }

  public getIsAuthorized() {
    return this._oidcSecurityService.getIsAuthorized();
  }
`

**Comment by profet23** [comment] 2018-12-12 14:45
@SolarMaximus 

I just want to double check... if you open a brand new incognito session. And attempt this, the timeout is still hit? I'm not sure how that would be possible. 

Keep in mind that if you open a brand new incognito...  and then try hitting the page a second time... you WILL hit the timeout. 

I'm curious about that first page load... is the timeout hit in that first page load?

**Comment by profet23** [comment] 2018-12-12 14:49
Basically this is what should be happening on the first load:

![image](https://user-images.githubusercontent.com/2411974/49877294-1a01b580-fdf3-11e8-8ebb-56ad88b8c800.png)


As you can see, it takes less then a tenth of a second.

**Comment by profet23** [comment] 2018-12-12 14:57
Basically, if you never process a successful login/validation the authNonce is never cleared. If the authNonce is not cleared, the process assumes validation/login is already in process and doesn't attempt another one. Since nothing is kicked off, the time out is eventually hit.

I'm just not sure how you are hitting this consistently. I can get it to happen if I load my app and never login. At that point if I keep going to the app page, it'll keep hitting the timeout. But I'm not sure if that's a bug. Since the user is doing some strange thing and never actually authenticating.

**Comment by SolarMaximus** [comment] 2019-01-10 13:49
What do you mean by processing a successful login/validation? I see the only place in code where authNonce can be cleared - handleSuccessfulValidation method. But I can't call it manually, because it is private. 
`    
StateValidationService.prototype.handleSuccessfulValidation = function () {
        this.oidcSecurityCommon.authNonce = '';
        if (this.authConfiguration.auto_clean_state_after_authentication) {
            this.oidcSecurityCommon.authStateControl = '';
        }
        this.loggerService.logDebug('AuthorizedCallback token(s) validated, continue');
    };
`
![image](https://user-images.githubusercontent.com/29251904/50972369-886f8b80-14f7-11e9-8051-ed657d8473dd.png)

This thing happens when I manually in console kill authNonce after accessing private page by anonymous user. It goes to the refresh_session method, where nonce is set and timeout happens again.

**Comment by SolarMaximus** [comment] 2019-01-10 15:00
Tried to update 6.0.12 to 9.0.0 - it remained the same. Can it be something wrong with this._oidcSecurityService.getIsAuthorized()? We use it to determine whether a user authenticated or not. Maybe we can use another options?

**Comment by hverma** [comment] 2019-02-09 16:11
I can confirm the same behavior as well. My default page is the home page which is a private page.
If the auth nonce exist and I don't delete it using console, it goes to the home page and takes 5 seconds to redirect to the public page. It used to be instantaneous. If I set silent renew = false the issue goes away.

**Comment by hverma** [comment] 2019-02-10 12:34
@damienbod  @profet23 seems like number of folks are hitting this issue. Any ideas?

**Comment by hverma** [comment] 2019-02-10 13:08
Hack to get us through for now. This code removes the authNonce set if a user goes to a private page and doesn't authenticate. In my case, it is routing to the public landing page.

`    if (!window.location.hash && localStorage.getItem("_isAuthorized_xxxx) !== "true") {
      localStorage.removeItem("authNonce_xxxx");
    }`

**Comment by earshinov** [comment] 2019-02-10 17:34
We seem to experience the same issue. Console logs:

```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Silent return url:  https://xxx/oidc/oidc-silent-renew.html
STS server: https://yyy
Silent Renew is active, check if token in storage is active
<iframe id=​"myiFrameForSilentRenew" src(unknown) srcdoc name style=​"display:​ none;​">​…​</iframe>​
IsAuthorizedRace: Timeout reached. Emitting.
IsAuthorizedRace: Completed
getIsAuthorized: false
```

**Comment by liri2006** [comment] 2019-03-05 21:01
@profet23, I'm facing the same issue. It is working just as you've described - first time it is instant with error "login_required" and second time there is a timeout. And all of this while navigating to public page (without even calling getIsAuthorized()).

**Comment by florisrobbemont** [comment] 2019-04-26 09:50
Any update on this? We are facing the same issue.

**Comment by damienbod** [comment] 2019-04-26 11:36
@florisrobbemont @liri2006  What issue are you facing exactly? We have a few different things on this thread.

**Comment by florisrobbemont** [comment] 2019-04-26 13:00
@damienbod 
We are facing the wait time of 5 seconds when the application first loads. We load the config using an APP_INITIALIZER and then call setupModule on the oidcSecurityService.

We have an AuthGuard on the routes we want to protect, where we call into oidcSecurityService.GetIsAuthorized(). Even on a fresh in-private browser it still takes 5 seconds before the user is redirected to the login site. If we place breakpoints on the AuthGuard we can clearly see that it takes that amount of time before our own code is executed.

It takes 5 seconds to get from breakpoint 1 to 2:
![image](https://user-images.githubusercontent.com/1893978/56808852-c7211b80-6832-11e9-957f-48b71085c240.png)

We have basically taken everything from the sample. Even the sample application with the default config shows the same behaviour:
![image](https://user-images.githubusercontent.com/1893978/56809391-000dc000-6834-11e9-8fe6-346f221c9130.png)

**Comment by damienbod** [comment] 2019-04-26 13:26
Ah ok, we should remove the 5s wait on init, thanks, will try to fix this, need to figure it out

**Comment by florisrobbemont** [comment] 2019-05-21 12:47
> Ah ok, we should remove the 5s wait on init, thanks, will try to fix this, need to figure it out

Hi @damienbod, Do you have an update for us? Is there something we can do as a work-around?
Hope to hear from you.

**Comment by damienbod** [comment] 2019-05-21 15:41
@florisrobbemont this issue got lost, very busy at the moment... We are doing a 10.0.0 release, I will add this in this release, or if it's simple, will do a quick release before. If you see how to fix it, you can do a PR, and I'll test and to a minor release. 

Greetings Damien

**Comment by florisrobbemont** [comment] 2019-05-21 16:49
@damienbod 
Unfortunately I don't know how to fix this. If you can ship this in a small release it would be very helpful for us.
What's the timetable on the 10.0.0 release?

**Comment by damienbod** [comment] 2019-05-21 18:28
release 10 will take about 2 weeks,  3 relative large things I want to improve. 1 PR is almost complete, just the docs and the testing, other things still todo, I'll see if I can fix this on Friday, have to look into it

Greetings Damien

**Comment by damienbod** [comment] 2019-05-21 20:12
I will release a fix for this in 9.0.8, have a fix now, just testing before I release

**Comment by damienbod** [comment] 2019-05-21 20:51
Released in 9.0.8

**Comment by florisrobbemont** [comment] 2019-05-21 21:36
@damienbod wow! Thnx! Will test this tomorrow right away!

**Comment by damienbod** [comment] 2019-05-21 22:27
@florisrobbemont 

I have a bit on a mess with the config for silent renew

at the moment, use both

config.silent_renew_url = 'https://localhost:44395/silent-renew.html',
config.silent_redirect_url = 'https://localhost:44395/silent-renew.html',

Will fix  this in version 10

**Comment by codemasterover9000** [comment] 2019-05-22 10:07
Hi, 

Just tested 9.0.8. But I get errors regarding nonce validation at this line:

`if (!this.oidcSecurityValidation.validate_id_token_nonce(toReturn.decoded_id_token, this.oidcSecurityCommon.authNonce))`

`this.oidcSecurityCommon.authNonce` has value "".

Initial login in a private tab works correctly. After logout and re-login it keeps failing at that line. And my app keeps stuck in an infinite auth loop (unauthorized->login at authserver->repeat).

Using implicit flow btw.

**Comment by damienbod** [comment] 2019-05-22 10:39
@codemasterover9000 

Could you compare your app to this implicit flow implementation:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.module.ts

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts

Just wondering what is different?  

Greetings Damien

**Comment by codemasterover9000** [comment] 2019-05-22 10:54
@damienbod Im using the code below. Works with version 8.0.3 which is what I'm currently using.

```
export function loadOIDCConfigFromAuthServer(oidcConfigService: OidcConfigService, authUri: string)
{
    return () => oidcConfigService.load_using_stsServer(authUri);
}

export function createOICImplicitFlowConfiguration(clientId: string)
{
    const redirectUrl = window.location.origin;
    const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();
    openIDImplicitFlowConfiguration.client_id = clientId;
    openIDImplicitFlowConfiguration.redirect_url = redirectUrl;
    openIDImplicitFlowConfiguration.post_logout_redirect_uri = redirectUrl;
    openIDImplicitFlowConfiguration.silent_renew = true;
    openIDImplicitFlowConfiguration.silent_renew_url = `${redirectUrl}/token-refresh.html`;
    openIDImplicitFlowConfiguration.trigger_authorization_result_event = true;
    openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 60;
    openIDImplicitFlowConfiguration.log_console_warning_active = true;

    return openIDImplicitFlowConfiguration;
}
```

**Comment by ivarsst** [comment] 2019-05-23 19:09
Hi,
have the same problem as @florisrobbemont. I am using **9.0.8. and code flow with PKCE**. The problem appears, when im trying to open my client application page from sts landing page and sometimes even on same client application page refresh with "F5". My client page taking long to respond, as it is pretty heavy (angular material and other fancy stuff). 
**Image from console:**
![2019_05_23_21_42_28_Dashboard](https://user-images.githubusercontent.com/7135036/58278377-8d492380-7da4-11e9-9f07-c9147ccae9dc.png)
**appsettings.json:**
`
"ClientAppSettings": {
    "stsServer": "https://localhost:44347",
    "redirect_url": "https://localhost:44378",
    "client_id": "angular_code_client",
    "response_type": "code",
    "scope": "dataEventRecords securedFiles openid profile",
    "post_logout_redirect_uri": "https://localhost:44378",
    "start_checksession": false,
    "silent_renew": true,
    "startup_route": "/",
    "forbidden_route": "/forbidden",
    "unauthorized_route": "/unauthorized",
    "log_console_warning_active": true,
    "log_console_debug_active": true,
    "max_id_token_iat_offset_allowed_in_seconds": 60,
    "apiServer": "https://localhost:44390/"
  }`

**AppModule.ts:**

`export function loadConfig(oidcConfigService: OidcConfigService) {
  console.log('APP_INITIALIZER STARTING');
  return () => oidcConfigService.load($"window.location.origin}/api/ClientAppSettings");
}`

`this.oidcConfigService.onConfigurationLoaded.subscribe(() => {
      const config = new OpenIDImplicitFlowConfiguration();
      config.stsServer = this.oidcConfigService.clientConfiguration.stsServer;
      config.redirect_url = this.oidcConfigService.clientConfiguration.redirect_url;
      config.client_id = this.oidcConfigService.clientConfiguration.client_id;
      config.response_type = this.oidcConfigService.clientConfiguration.response_type;
      config.scope = this.oidcConfigService.clientConfiguration.scope;
      config.post_logout_redirect_uri = this.oidcConfigService.clientConfiguration.post_logout_redirect_uri;
      config.start_checksession = this.oidcConfigService.clientConfiguration.start_checksession;
      config.silent_renew = this.oidcConfigService.clientConfiguration.silent_renew;
      config.silent_renew_url = this.oidcConfigService.clientConfiguration.redirect_url + '/silent-renew.html';
      config.post_login_route = this.oidcConfigService.clientConfiguration.startup_route;
      config.forbidden_route = this.oidcConfigService.clientConfiguration.forbidden_route;
      config.unauthorized_route = this.oidcConfigService.clientConfiguration.unauthorized_route;
      config.log_console_warning_active = 
     this.oidcConfigService.clientConfiguration.log_console_warning_active;
      config.log_console_debug_active = 
     this.oidcConfigService.clientConfiguration.log_console_debug_active;
      config.max_id_token_iat_offset_allowed_in_seconds = 
     this.oidcConfigService.clientConfiguration.max_id_token_iat_offset_allowed_in_seconds;
      configuration.FileServer = this.oidcConfigService.clientConfiguration.apiFileServer;
      configuration.Server = this.oidcConfigService.clientConfiguration.apiServer;
      this.oidcSecurityService.setupModule(config, this.oidcConfigService.wellKnownEndpoints);
    });`

**STS client config:**

` new Client
                {
                    
                    ClientName = "angular_code_client",
                    ClientId = "angular_code_client",
                    AccessTokenType = AccessTokenType.Reference,
                    // RequireConsent = false,
                    AccessTokenLifetime = 330,// 330 seconds, default 60 minutes
                    IdentityTokenLifetime = 30,

                    RequireClientSecret = false,
                    AllowedGrantTypes = GrantTypes.Code,
                    RequirePkce = true,

                    AllowAccessTokensViaBrowser = true,
                    RedirectUris = new List<string>
                    {
                        "https://localhost:44378",
                        "https://localhost:44378/silent-renew.html",
                        "https://localhost:4200",
                        "https://localhost:4200/silent-renew.html"
                    },
                    PostLogoutRedirectUris = new List<string>
                    {
                        "https://localhost:44378/unauthorized",
                        "https://localhost:44378",
                        "https://localhost:4200/unauthorized",
                        "https://localhost:4200"
                    },
                    AllowedCorsOrigins = new List<string>
                    {
                        "https://localhost:44378",
                        "https://localhost:4200"
                    },
                    AllowedScopes = new List<string>
                    {
                        "openid",
                        "dataEventRecords",
                        "dataeventrecordsscope",
                        "securedFiles",
                        "securedfilesscope",
                        "role",
                        "profile",
                        "email"
                    }
                }`

**Comment by florisrobbemont** [comment] 2019-05-23 20:43
We have implemented the new version, and have noticed that the 5 second delay is gone for around 60% of times. The other 40% we’re still seeing this delay. It seems that this wait time is still being triggered somehow.

**Comment by florisrobbemont** [comment] 2019-07-29 10:38
I think we need to re-open this. We're still getting the 5 seconds wait time, even with the new 10 release.

**Comment by beto** [comment] 2019-08-20 18:25
Yes, agreed.  Updated to 10.0.3 and I am still getting the 5 second wait time. Thank you

**Comment by damienbod** [comment] 2019-09-14 08:50
configuration added for this now

**Closed by damienbod** 2019-09-14 08:50 UTC
Labels: enhancement, investigate

**Comment by beto** [comment] 2019-09-17 23:16
@damienbod than you for the work around, this is working for us.

**Comment by Chiru1610** [comment] 2020-10-01 17:39
@beto @damienbod: We are tried angular CLI 8.3.0 with angular-auth-oidc-client: 10.0.3 and we still see 5 seconds delay ..Can someone help/inform us what is the workaround?

**Comment by gmat275** [comment] 2023-09-15 17:45
@beto @damienbod  @Chiru1610 I'm encountering this same problem and also interested in finding out about the workaround.  Is it necessary to drop back to 10.0.14 or is there a way to make 10.0.15 work?
