### ISSUE TITLE
[Question]: Multiple Pop Up Logins Causes null errors

### ISSUE THREAD

**Issue by lewdi4** [damienbod/angular-auth-oidc-client#1562] opened 2022-10-21 16:16 UTC
**What Version of the library are you using?**
14.1.5

**Question**
When a user clicks a button to launch the popup, sometimes they don't see the popup or pop another popup.  when the user submits that popup, I am getting null pointer errors that are crashing chrome. Is there some way to manager the popup so it automatically pops the same window, or so that it will ignores the second popup request?

**Comment by FabianGosebrink** [comment] 2022-10-29 11:08
Hey, what do you mean with "pop another popup"? Do you mean that they click the button multiple times? And then, when they close one of the first popups, they get an error? Thanks

**Comment by lewdi4** [comment] 2022-10-29 18:04
Yes.  When they click the buttons the first time the first pop shows.  If they ignore that pop up and click the button again and submit it,  the app has an endless loop of errors.

Michael Ladewski

On Oct 29, 2022, at 7:08 AM, Fabian Gosebrink ***@***.***> wrote:

﻿

Hey, what do you mean with "pop another popup"? Do you mean that they click the button multiple times? And then, when they close one of the first popups, they get an error? Thanks

**Comment by FabianGosebrink** [comment] 2022-11-03 07:19
Duplicate of #1333

**Comment by fritzwf** [comment] 2022-11-04 17:30
Can the pop-up be made so the minimize option can be disabled?  Also, if there is already a modal pop-up, don't let it create another one.  I also see the issue:

`login.component.ts:82 ERROR TypeError: Cannot read properties of null (reading 'closed')
      at angular-auth-oidc-client.mjs:3966:28
      at timer (zone.js:2405:41)
      at _ZoneDelegate.invokeTask (zone.js:406:31)
      at Object.onInvokeTask (core.mjs:26194:33)
      at _ZoneDelegate.invokeTask (zone.js:405:60)
      at Zone.runTask (zone.js:178:47)
      at invokeTask (zone.js:487:34)
      at ZoneTask.invoke (zone.js:476:48)
      at data.args.<computed> (zone.js:2385:32)`

Once this error is thrown, it creates an infinite loop inside of the module somewhere.

Regards

**Comment by FabianGosebrink** [comment] 2022-11-04 20:32
I think we will fix the issue that no other popup can be opened when a popup is already open.

**Comment by lewdi4** [comment] 2022-11-18 21:33
Was this fixed in version 15?  I see the issue still occurring.

**Comment by FabianGosebrink** [comment] 2022-11-22 08:54
We are on it with the upcoming PR.

**Comment by FabianGosebrink** [comment] 2022-11-27 07:51
Should be fixed in 15.0.1

**Closed** 2022-11-27 07:51 UTC
Labels: question
