### ISSUE TITLE
Refresh session clears access token when ID token not included in refresh request

### ISSUE THREAD

**Issue by perryadams** [damienbod/angular-auth-oidc-client#1039] opened 2021-04-06 13:10 UTC
We are using Ping for STS authentication.  When we post a request to refresh the access token, Ping does not provide the ID token in the response and as a result the new access token and refresh token is not stored.
I was able to reproduce the issue using the sample-code-flow-refresh-tokens.  I ran the sample application as is to see that it worked successfully using the "Refresh session" button.
I modified the auth-config.module.ts changing stsServer and clientId to use our STS server.  After logging in, I selected the "Refresh session" button.  Below is the console logs.  Notice the last line logs 'null' as the result from the subscription to the oidcSecurityService.forceRefreshSession.  Calls to oidcSecurityService.getToken() or oidcSecurityService.getRefreshToken() also return 'null'.
Also note the log line 'No id_token found, skipping id_token validation'

This was the response to the refresh_token request:  {"access_token":"0008Zj7xXrwczRGrDjAeujLOAZut","refresh_token":"9UvJjD7DZ47Q7NLthtsjxR54YqpIc8X9d8jYYg2jTs","token_type":"Bearer","expires_in":7199}

### Console Log:
angular-auth-oidc-client.js:274 Wanted to read 'abcClient_storageSilentRenewRunning' but nothing was found
angular-auth-oidc-client.js:274 Checking: silentRenewRunning: false
angular-auth-oidc-client.js:274 BEGIN refresh session Authorize
angular-auth-oidc-client.js:274 RefreshSession created. adding myautostate: 4f2ca6847119a7feacaecbb35b9c91572eRZTJZXB
angular-auth-oidc-client.js:274 found refresh code, obtaining new credentials with refresh code
angular-auth-oidc-client.js:271 token refresh response:  {access_token: "0008Zlpt4sBYB3emrwrnlmEAT1cG", refresh_token: "ZXRfJNolWD2wb4tXW7xgUxWD4JkyoTRB2yfhf7rFKT", token_type: "Bearer", expires_in: 7199}
angular-auth-oidc-client.js:274 history clean up inactive
angular-auth-oidc-client.js:274 {access_token: "0008Zlpt4sBYB3emrwrnlmEAT1cG", refresh_token: "ZXRfJNolWD2wb4tXW7xgUxWD4JkyoTRB2yfhf7rFKT", token_type: "Bearer", expires_in: 7199, state: "4f2ca6847119a7feacaecbb35b9c91572eRZTJZXB"}
angular-auth-oidc-client.js:274 authorizedCallback created, begin token validation
angular-auth-oidc-client.js:271 Getting signinkeys from  https://sso-uat.service.vumc.org/pf/JWKS
angular-auth-oidc-client.js:274 **No id_token found, skipping id_token validation**
angular-auth-oidc-client.js:274 AuthorizedCallback token(s) validated, continue
angular-auth-oidc-client.js:274 0008Zlpt4sBYB3emrwrnlmEAT1cG
angular-auth-oidc-client.js:274 storing the accessToken
home.component.ts:29 authenticated:  true
home.component.ts:39 **refreshSession: result=null**

**Comment by perryadams** [comment] 2021-04-06 15:50
I tried including the 'offline_access' scope but receive an invalid_scope error

**Comment by damienbod** [comment] 2021-04-06 18:17
linked to this https://github.com/damienbod/angular-auth-oidc-client/issues/996

**Comment by FiReBlUe45** [comment] 2021-04-19 08:38
any news?

**Comment by damienbod** [comment] 2021-04-19 09:22
@FiReBlUe45 yes I plan to understand this, fix this, didn't have time to do it this weekend, it's high on my TODO list

**Comment by damienbod** [comment] 2021-04-30 20:18
Hi @FiReBlUe45 I created an account with ping identity and test this. I can't reproduce this bug, ping returns an id_token when I refresh and I can't reproduce this error.

I would need further info to fix this.

On ping I use code flow with PKCE

```
export function configureAuth(oidcConfigService: OidcConfigService) {
  return () =>
    oidcConfigService.withConfig({
      stsServer: 'https://auth.pingone.eu/45a3c6e1-f8af-43c2-84ea-330e646da32c/as',
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
      clientId: '0c0e1c9a-21fb-4d87-a936-772e052a19d8',
      scope: 'openid profile',
      responseType: 'code',
      silentRenew: true,
      useRefreshToken: true,
      logLevel: LogLevel.Debug,
    });
```

**Comment by FiReBlUe45** [comment] 2021-05-04 07:58
Hi @damienbod, precisely my IDP server does not return the token ID at the time of the refresh. This is not mandatory information in the RFC.

Here is my configuration

```
      stsServer: 'http://authz.int.xxxxx.xx',
      redirectUrl: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
      clientId: 'myapp:client',
      scope: 'openid profile', 
      responseType: 'code',
      silentRenew: true,
      silentRenewUrl: `${window.location.origin}/silent-renew.html`,
      useRefreshToken: true,
      renewTimeBeforeTokenExpiresInSeconds: 10,
      logLevel: LogLevel.Debug,
      autoUserinfo: true,
      startCheckSession: false,
      triggerAuthorizationResultEvent: true,
      silentRenewTimeoutInSeconds: 15,
      maxIdTokenIatOffsetAllowedInSeconds: 10,
```

**Comment by FiReBlUe45** [comment] 2021-05-12 09:27
Hi @damienbod,

I looked at your code.

In STEP 4 All flows:
Call => ```this.stateValidationService.getValidatedStateResult(callbackContext)```

In state-validation.service.ts line 55:
You check  ```if (callbackContext.authResult.id_token)``` but  my IDP server doesn't return the id_token because for refresh call, this isn't mandatory information in the RFC.

We should keep the id_token of the initial connection and not delete  it when the refresh process begins.

**Comment by damienbod** [comment] 2021-05-13 10:08
@FiReBlUe45 I need to reproduce this to validate, fix etc, can you setup an IDP and example so I can reproduce?

Greetings Damien

**Comment by FiReBlUe45** [comment] 2021-05-14 09:21
@damienbod I can try to provide you with a Cypress test to simulate the behavior of my OAuth server. Do you want to?

**Comment by petersandor** [comment] 2021-07-01 19:17
> We should keep the id_token of the initial connection and not delete it when the refresh process begins.

Existing state with `id_token` is simply overwritten with the token refresh response, which essentially deletes it in this write operation:

https://github.com/damienbod/angular-auth-oidc-client/blob/3de72d57b53f479f946d30b9b77a5bfa975aec79/projects/angular-auth-oidc-client/src/lib/flows/callback-handling/history-jwt-keys-callback-handler.service.ts#L29-L31

And after that it starts to validate the state

https://github.com/damienbod/angular-auth-oidc-client/blob/3de72d57b53f479f946d30b9b77a5bfa975aec79/projects/angular-auth-oidc-client/src/lib/flows/flows.service.ts#L55-L56

But then `id_token` is no longer present.

@damienbod would it make sense to merge instead of overwrite the auth state so that `id_token` is preserved?

**Comment by bas-be** [comment] 2021-08-16 12:36
PingFederate introduced a new property to include the id_token in the refresh response in v10:
https://docs.pingidentity.com/bundle/pingfederate-100/page/jzv1564002996192.html

**Comment by damienbod** [comment] 2021-11-08 06:37
Closing this as Angular is now V13

**Closed by damienbod** 2021-11-08 06:37 UTC
Labels: Cannot be reproduced, version 11, no_id_token_returned_refresh_flow

**Comment by petersandor** [comment] 2021-11-15 10:24
> Closing this as Angular is now V13

@damienbod Does that mean that this issue is now resolved?

**Comment by damienbod** [comment] 2021-11-15 10:45
Hi @petersandor this issue is on version 11 and we are now focusing on issues, for Angular 12/13 and the lib version 12. I could not reproduce on the V12 version.

Greetings Damien

**Comment by petersandor** [comment] 2021-11-25 21:47
> Hi @petersandor this issue is on version 11 and we are now focusing on issues, for Angular 12/13 and the lib version 12. I could not reproduce on the V12 version.
> 
> Greetings Damien

The same logic I commented on in https://github.com/damienbod/angular-auth-oidc-client/issues/1039#issuecomment-872490382 is still in this repository as of today, which means when you use providers which do not include the `id_token` in refresh response the client will again simply destructively overwrite the local state and remove the `id_token` in the following call

https://github.com/damienbod/angular-auth-oidc-client/blob/b19ee5fecee7cade5a37e98bcb87e589a4df0731/projects/angular-auth-oidc-client/src/lib/flows/callback-handling/history-jwt-keys-callback-handler.service.ts#L31

@damienbod If you can test this with such provider (which doesn't include `id_token` in refresh response) and confirm that would be greatly appreciated. If it was already resolved, could you please share a link to the commit that fixed it? Thank you.

**Comment by vroom-vroom** [comment] 2021-12-01 08:53
I have similar issues with having no id_token in refresh token response.
Even with
- enableIdTokenExpiredValidationInRenew: false
- disableRefreshIdTokenAuthTimeValidation: true
renewal is not rescheduled without id_token and default interceptor implementation for secureRoutes stops attaching access_token to requests despite that we have fresh access_token in session storage and access_token_expires_at have some valid time (not in the past).
Tried to manually (using iterceptor) to attach old id_token to response but then renewal is scheduled immidiatelly resulting in infinite loop of refresh token requests.

**Comment by agardiol** [comment] 2022-03-11 11:02
I have the same issue on version 13.1, even with 
```
    enableIdTokenExpiredValidationInRenew: false,
    disableRefreshIdTokenAuthTimeValidation: true,
```
Access token in default interceptor becomes null event if refresh process with auth server went well and service return following debug message:
`[DEBUG] 0-d6Q8RvJs5ldseCouCndOsRKMsmH2Dq3p2oYqHC1b - token refresh response:  {access_token: 'xxx', expires_in: 60, token_type: 'Bearer', scope: 'openid read write', refresh_token: 'xxx'}`
