### ISSUE TITLE
Optional configuration to exclude the id token from auth checks

### ISSUE THREAD

**Issue by PhilippSonntagORGADATA** [damienbod/angular-auth-oidc-client#1177] opened 2021-07-07 15:57 UTC
**Is your feature request related to a problem? Please describe.**
Our problem is that the id token provided by our identity provider has a very short lifetime and expires within 5 minutes. According to most documentations this behavior is correct as the id token should only be used initially to get user information.
Due to the expiration, the user in the app will get logged out, even though the access token is still valid and can be used to get resources.

**Describe the solution you'd like**
Add a new boolean to the configuration of the library. The property should exclude the id token from the checkAuth, so the authentication state can be validated without the id token in mind. This property is optional and will change the current behavior only when manually set. 

**Describe alternatives you've considered**
- Refreshing the id token via a silent renew and iframe
   - It's not recommended anymore for newer applications. [see here](https://leastprivilege.com/2020/03/31/spas-are-dead/)
   - Doesn't work with the content security policy of our idp
- Refresh tokens
  - According to the standard, [the id token don't has to be refreshed](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) when using the refresh token
  - Even if it's refreshed, it's already expired as just the iat has to be refreshed

**Additional context**
- Already took a look at the last [issue](https://github.com/damienbod/angular-auth-oidc-client/pull/780) of this topic, but I think it's not solved

**Comment by FabianGosebrink** [comment] 2021-07-12 05:58
Have you checked the config option? [enableIdTokenExpiredValidationInRenew](https://nice-hill-002425310.azurestaticapps.net/docs/documentation/configuration#enableidtokenexpiredvalidationinrenew)

**Comment by bas-be** [comment] 2021-07-15 15:30
I'm also using an IDP (Ping) which is not including a new id_token in the refresh respone.

@FabianGosebrink I tried to use the config option, but unfortunately I'm stuck with angular 11 for now. Therefore I made a fork of 11 and merged the new config option. It seems like this is not sufficient because additional validations require the id token to be available. Removing these validations did work, but is not an acceptable solution. Maybe these lines have to be adjusted in case the new config option ist set as well?

https://github.com/damienbod/angular-auth-oidc-client/blob/26bd4bb7d0ec04f996c8b88043991da07102e7c7/projects/angular-auth-oidc-client/src/lib/callback/periodically-token-check.service.ts#L151

https://github.com/damienbod/angular-auth-oidc-client/blob/26bd4bb7d0ec04f996c8b88043991da07102e7c7/projects/angular-auth-oidc-client/src/lib/auth-state/auth-state.service.ts#L152-L154

I also tried to just keep the old id token if the refresh response does not include a new one, but this is causing the other id_token checks to fail.

I think that there a multiple open issues, which are all connected to the missing id_token in the token refresh:

#1190 
#1039 

I personally agree with @PhilippSonntagORGADATA that the id token should not be validated after the first authentication result, but I can also understand why it's checked periodically here. I found a nice post about this: [https://developer.okta.com/blog/2019/06/05/seven-ways-an-oauth-access-token-is-like-a-hotel-key-card](url)

**Comment by damienbod** [comment] 2021-07-25 09:27
Would it be possible to setup a test ping IDP which we can test against?

Greetings Damien

**Comment by gbenthomas** [comment] 2021-07-26 23:21
Hi Damien. I've been following these issues for a while now and I would like to help you reproduce it. However, I'd rather not post the URL here. Can I send you details over Twitter? Please message me at @ g_ben_thomas or let me know if you prefer some other way. Thanks.

**Comment by damienbod** [comment] 2021-07-27 06:46
Here's my twitter https://twitter.com/damien_bod

**Comment by gbenthomas** [comment] 2021-07-27 12:38
I can't send you a DM. I think it's a privacy setting on your end.

**Closed** 2021-11-08 06:38 UTC
Labels: More information needed, no_id_token_returned_refresh_flow
